"""
WoundCare AI - Abbreviation Memory Store
Centralized repository of clinical abbreviations for decoding handwritten notes and dictations.
"""

ABBREVIATION_STORE = {
    "Wound Types": {
        "Art": "Arterial ulcer",
        "AU": "Arterial ulcer",
        "D": "Diabetic ulcer",
        "DM": "Diabetic ulcer",
        "DU": "Diabetic ulcer",
        "Diab": "Diabetic ulcer",
        "Wag+#": "Diabetic ulcer + grade number",
        "DTI": "Deep tissue injury",
        "ST1": "Stage 1 Pressure Injury",
        "ST2": "Stage 2 Pressure Injury",
        "ST3": "Stage 3 Pressure Injury",
        "ST4": "Stage 4 Pressure Injury",
        "UNST": "Unstageable Pressure Injury",
        "VU": "Venous leg ulcer",
        "Ven": "Venous leg ulcer",
        "VLU": "Venous leg ulcer",
        "Absc": "Abscess",
        "AR": "Allergic reaction",
        "BP": "Bullous pemphigoid",
        "Fung": "Fungal dermatitis",
        "Lac": "Laceration",
        "Lymph": "Lymphedema",
        "CA": "Malignant wound",
        "Neuro": "Neuropathic ulcer",
        "Rad": "Radiation wound",
        "ST": "Skin tear",
        "Surg": "Surgical wound",
        "IAD": "Incontinence associated dermatitis",
        "MASD": "Moisture associated skin damage",
        "MDRPI": "Medical device related pressure injury"
    },
    "Wound Locations": {
        "LUQ": "Left upper quadrant (abdomen)",
        "LLQ": "Left lower quadrant (abdomen)",
        "RUQ": "Right upper quadrant (abdomen)",
        "RLQ": "Right lower quadrant (abdomen)",
        "Mid": "Midline",
        "AKA": "Above knee amputation",
        "BKA": "Below knee amputation",
        "TMA": "Transmetatarsal amputation",
        "LL": "Lower legs",
        "GT": "Great toe",
        "Isch": "Ischial",
        "FA": "Forearm",
        "Troch": "Trochanter",
        "L": "Left",
        "R": "Right",
        "BL": "Bilateral",
        "Dors": "Dorsal",
        "Plant": "Plantar",
        "MED": "Medial",
        "LAT": "Lateral",
        "ANT": "Anterior",
        "POST": "Posterior",
        "PROX": "Proximal",
        "Dist": "Distal",
        "INF": "Inferior",
        "SUP": "Superior"
    },
    "Exudate": {
        "LS": "Serous large",
        "SL": "Serous large",
        "S": "Serous scant",
        "SCANT": "Serous scant",
        "SEROSANG": "Serosanguineous",
        "SSM": "Serosanguineous moderate",
        "SM": "Serous moderate",
        "SS": "Serous small",
        "P": "Purulent",
        "C": "Copious",
        "MOD": "Moderate"
    },
    "Tissue / Wound Bed": {
        "B": "Black",
        "BD": "100% black discoloration",
        "BE": "Black eschar",
        "DHE": "Dry, hard eschar",
        "DHS": "Dry, hard scabbing",
        "DE": "Dry eschar",
        "MB": "Moist black",
        "DY": "Dry/adherent yellow slough",
        "ADS": "Dry/adherent yellow slough",
        "EPI": "Epithelial tissue",
        "D": "Dermis exposed",
        "G": "Granulation",
        "HG": "Hypergranulation",
        "Y": "Yellow slough",
        "YS": "Yellow slough",
        "Gang": "Gangrene",
        "NEC": "Necrotic",
        "TUN": "Tunneling",
        "UM": "Undermining"
    },
    "Periwound / Exposed Structures": {
        "+BONE": "Bone exposure",
        "ERY": "Erythema",
        "ERYTH": "Erythema",
        "EXC": "Excoriation",
        "MAC": "Maceration",
        "MACE": "Maceration",
        "+MUSCLE": "Muscle exposure",
        "+MUSC": "Muscle exposure",
        "PW": "Periwound",
        "+TENDON": "Tendon exposure",
        "+Muscle Nec": "Muscle necrosis"
    },
    "Procedures / Debridement": {
        "CAUT": "Cautery",
        "ND": "No debridement",
        "NPWT": "Negative pressure wound therapy",
        "SDM": "Debridement: skin, subcut. tissue, muscle, fascia",
        "SDS": "Debridement: skin, subcutaneous tissue",
        "CP": "Callus pared",
        "ACE-A": "ACE wraps applied",
        "I&D": "Incision and drainage",
        "Unna-A": "Unna boot applied",
        "NCF": "Non-contact immunofluorescence imaging",
        "F(-)": "Fluorescence negative",
        "F(+)": "Fluorescence positive",
        "C": "Cyan immunofluorescence",
        "R": "Red immunofluorescence",
        "C+R": "Cyan and red immunofluorescence",
        "-C": "Center",
        "-P": "Periphery",
        "C+P": "Wound center and periphery",
        "BG": "Bordered Gauze",
        "Allo": "Allograft",
        "Med": "Medihoney",
        "NCP": "Non-contact procedure",
        "QD": "Once daily",
        "BID": "Twice daily",
        "TID": "Three times daily",
        "QID": "Four times daily",
        "QOD": "Every other day",
        "PRN": "As needed",
        "HS": "At bedtime",
        "scab": "Scabbed",
        "post": "Posterior",
        "ant": "Anterior",
        "lat": "Lateral",
        "med": "Medial",
        "Rx": "Prescription",
        "ETB": "Extension to border",
        "B-20": "Biofilm-20",
        "V-20": "Vascular-20"
    },
    "Wound Status / Symbols": {
        "↑": "Wound improving",
        "↓": "Wound deteriorating",
        "=": "Wound stable / unchanged",
        "①": "Wound 1",
        "②": "Wound 2",
        "③": "Wound 3",
        "④": "Wound 4",
        "⑤": "Wound 5",
        "⑥": "Wound 6",
        "⑦": "Wound 7",
        "⑧": "Wound 8",
        "⑨": "Wound 9",
        "⑩": "Wound 10",
        "W/C": "Wheelchair",
        "W/O": "Without",
        "AO3": "Alert and oriented ×3",
        "D/W": "Discussed with",
        "PAD": "Peripheral arterial disease",
        "FAC": "Facility acquired",
        "POA": "Present on admission",
        "AF": "Atrial fibrillation",
        "HTN": "Hypertension",
        "HLD": "Hyperlipidemia",
        "CVI": "Chronic venous insufficiency",
        "ISO": "Isolation",
        "PVD": "Peripheral vascular disease",
        "S/P": "Status post",
        "TPN": "Total parenteral nutrition",
        "SNF": "Skilled nursing facility",
        "ALF": "Assisted living facility"
    }
}

def get_abbreviation_markdown() -> str:
    """Returns the store formatted as a markdown table for the prompt."""
    md = ""
    for category, items in ABBREVIATION_STORE.items():
        md += f"### {category}\n"
        md += "| Abbrev | Meaning |\n|---|---|\n"
        for abbrev, meaning in items.items():
            md += f"| {abbrev} | {meaning} |\n"
        md += "\n"
    return md
